Add valueStringifier for reporting
lostfictions/znv pull request #9
Opened 2023-07-23 17:21 UTC by pimartin

This PR adds an optional `valueStringifier` property in the `DetailedSpec` that allows the user to customize the way the received value is displayed in the errors report.

This allows secrets to be redacted to prevent them from appearing in the logs for example.

If not provided, it defaults to using `JSON.stringify`, thus preserving backward compatibility.

2023-08-30 02:40 UTC, lostfictions requested changes
thanks for the contribution (and sorry to be slow to get around to a review). this seems reasonable to me.

could you maybe add a few tests for this? feel free to simply add them to `parse-env.test.ts` for now.

what's the expected behaviour if `valueStringifier` throws?

2023-08-30 02:40 UTC, lostfictions commented on README.md
> +
thanks for adding documentation! looks like you inserted this in between the description of `defaults` and its example, so it should be moved downwards. could you also add the use-case of redacting values that you wrote up in the docstring?

2023-09-04 10:02 UTC, pimartin commented
Thanks for your comments, I will update the PR in accordance.

2023-09-05 03:44 UTC, lostfictions commented
As a heads up, I've been thinking about this a bit this past week alongside how to fix #2 -- I may introduce a more low-level API for printing values that allows more fine-grained control over printing (including colorization), as well as a "compatibility" entrypoint whose default stringifier performs no colorization at all (to unblock usage on edge runtimes and in the browser). So things may shift around a bit -- feel free to hold off for now, I'll keep this use case in mind!

2025-03-23 00:35 UTC, lostfictions commented
With #15, znv now allows specifying a custom reporter/formatter.

2025-03-23 00:35 UTC, closed without merging

2025-03-24 15:04 UTC, pimartin commented
Awesome, thanks!